name: Create ADM VA
on: [workflow_dispatch]
jobs:
  build:
    name: Build HelloWorld native-image on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      
      - name: Build 
        run: |
          mvn package
          java -jar sbom-utils.jar target/NativeHelloWorld.cdx.sbom.json --output=target/NativeHelloWorld.app-deps.json

      - name: Create ADM Vuln.Audit
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        id: create-adm-va
        with:
          command: 'adm vulnerability-audit create --knowledge-base-id=${{ secrets.ADM_KB }} --compartment-id=${{ secrets.ADM_VA_COMPART }} --display-name="native-hello-world-2" --build-type="MAVEN" --application-dependencies=file://target/NativeHelloWorld.app-deps.json --configuration=file://oci/adm-va-config.json'
          query: "data.id"
          silent: false

      - name: Sleep 
        run: |
          sleep 30s
          echo ${{ steps.create-adm-va.outputs.raw_output }}
          echo ${{ steps.create-adm-va.outputs.output }}

      - name: GET ADM Vuln.Audit
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        id: get-adm-va
        with:
          command: adm vulnerability-audit get --debug --vulnerability-audit-id ${{ steps.create-adm-va.outputs.raw_output }}
          
      - name: Display VA
        run: |
          echo ${{ steps.get-adm-va.outputs.output }} | jq .
