name: Buld with ADM Vuln.Audit
on: [workflow_dispatch]
jobs:
  build:
    name: Build HelloWorld native-image on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      
      - name: Build 
        run: |
          mvn package
          java -jar sbom-utils.jar target/NativeHelloWorld.cdx.sbom.json --output=target/NativeHelloWorld.app-deps.json

      - name: Create ADM Vuln.Audit
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        id: create-adm-va
        with:
          command: 'adm vulnerability-audit create --knowledge-base-id=${{ secrets.ADM_KB }} --compartment-id=${{ secrets.ADM_VA_COMPART }} --display-name="native-hello-world-2" --build-type="MAVEN" --application-dependencies=file://target/NativeHelloWorld.app-deps.json --configuration=file://oci/adm-va-config.json'
          query: "data.id"

      - name: ADM Wait for VA (30s)
        id: adm-wait-va
        run: |
          sleep 30s
          echo "ADM_VA_ID=${{ steps.create-adm-va.outputs.output }}" | sed 's/\"//g' >> $GITHUB_ENV

      - name: GET ADM Vuln.Audit
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        id: get-adm-va
        with:
          command: "adm vulnerability-audit get --vulnerability-audit-id=${{ env.ADM_VA_ID }}"
          query: "data"
          
      - name: Evaluate Vuln.Audit
        run: |
          VA_RESULT=$(echo ${{ steps.get-adm-va.outputs.output }} | jq -jr '."is-success",."lifecycle-state"')
          VULNS=$(echo ${{ steps.get-adm-va.outputs.output }} | jq -r '.vulnerabilities') >> GITHUB_STEP_SUMMARY

          if [ "$VA_RESULT" != "trueACTIVE" ]; then
            echo "### FAILED Vulnerability Audit:\n${VULNS}" >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            echo "### PASSED Vulnerability Audit :rocket:" >> $GITHUB_STEP_SUMMARY
          fi  
